site-update_notifier/config/routes.rb
SiteUpdateNotifier::Application.routes.draw do
  resources :relationships

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help', via: [:get, :post]
  match '/about',   to: 'static_pages#about', via: [:get, :post]
  match '/contact', to: 'static_pages#contact', via: [:get, :post]

  match 'sessions/new', to: 'sessions#new', via: [:get, :post]
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match "/logout", to: "sessions#destroy", :as => "logout", via: [:get, :post]

  resources :identities
  resources :microposts
  resources :users
  resources :resources
  resources :resource

end

site-update_notifier/app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul class= "footer_info">
      <li><%= link_to "About", about_path%></li>
    </ul>
  </nav>
</footer>

site-update_notifier/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "About", about_path%></li>
          <% if current_user %>
            <li><a href="<%= user_path(current_user) %>">Account information</a></li>
          <% else %>
            <li><%= link_to "Sign in", root_path %></li>
          <% end %>
          
          <li><%= link_to "Log out", logout_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

site-update_notifier/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

site-update_notifier/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class="main white">
      <%= yield %>
    </div>
  </body>
</html>