site-update_notifier/config/routes.rb
SiteUpdateNotifier::Application.routes.draw do
  resources :relationships

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help', via: [:get, :post]
  match '/about',   to: 'static_pages#about', via: [:get, :post]
  match '/contact', to: 'static_pages#contact', via: [:get, :post]

  match 'sessions/new', to: 'sessions#new', via: [:get, :post]
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match "/logout", to: "sessions#destroy", :as => "logout", via: [:get, :post]

  resources :identities
  resources :microposts
  resources :users
  resources :resources
  resources :resource

end

site-update_notifier/app/models/relationship.rb
# == Schema Information
#
# Table name: relationships
#
#  id          :integer          not null, primary key
#  follower_id :integer
#  followed_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Relationship < ActiveRecord::Base
  belongs_to :follower, :class_name => "User"
  belongs_to :followed, :class_name => "User"
  
  validates :follower_id, :presence => true
  validates :followed_id, :presence => true
end

site-update_notifier/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: [:show, :edit, :update, :destroy]

  # POST /relationships
  # POST /relationships.json
  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json
  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relationship
      @relationship = Relationship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relationship_params
      params.require(:relationship).permit(:follower_id, :followed_id)
    end
end

site-update_notifier/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

site-update_notifier/app/views/relationships/_form.html.erb
<%= form_for(@relationship) do |f| %>
  <% if @relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relationship.errors.count, "error") %> prohibited this relationship from being saved:</h2>

      <ul>
      <% @relationship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :follower_id %><br>
    <%= f.number_field :follower_id %>
  </div>
  <div class="field">
    <%= f.label :followed_id %><br>
    <%= f.number_field :followed_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

site-update_notifier/app/views/relationships/edit.html.erb
<h1>Editing relationship</h1>

<%= render 'form' %>

<%= link_to 'Show', @relationship %> |
<%= link_to 'Back', relationships_path %>

site-update_notifier/app/views/relationships/index.html.erb
<h1>Listing relationships</h1>

<table>
  <thead>
    <tr>
      <th>Follower</th>
      <th>Followed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @relationships.each do |relationship| %>
      <tr>
        <td><%= relationship.follower_id %></td>
        <td><%= relationship.followed_id %></td>
        <td><%= link_to 'Show', relationship %></td>
        <td><%= link_to 'Edit', edit_relationship_path(relationship) %></td>
        <td><%= link_to 'Destroy', relationship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relationship', new_relationship_path %>

site-update_notifier/app/views/relationships/new.html.erb
<h1>New relationship</h1>

<%= render 'form' %>

<%= link_to 'Back', relationships_path %>

site-update_notifier/app/views/relationships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Follower:</strong>
  <%= @relationship.follower_id %>
</p>

<p>
  <strong>Followed:</strong>
  <%= @relationship.followed_id %>
</p>

<%= link_to 'Edit', edit_relationship_path(@relationship) %> |
<%= link_to 'Back', relationships_path %>