site-update_notifier/config/routes.rb
SiteUpdateNotifier::Application.routes.draw do
  resources :relationships

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help', via: [:get, :post]
  match '/about',   to: 'static_pages#about', via: [:get, :post]
  match '/contact', to: 'static_pages#contact', via: [:get, :post]

  match 'sessions/new', to: 'sessions#new', via: [:get, :post]
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match "/logout", to: "sessions#destroy", :as => "logout", via: [:get, :post]

  resources :identities
  resources :microposts
  resources :users
  resources :resources
  resources :resource

end

site-update_notifier/app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <p>It's time to be used to update (seconds, default: 60 seconds)</p> <br>
    <%= f.number_field :timeout %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

site-update_notifier/app/views/resources/_resource.html.erb
<tr>
  <td>
    <a href="<%= resource.url %>"><%= resource.name %></a>
  </td>
  <td>
    <%= resource.timeout %>
  </td>
  <td>
    <%= link_to 'Edit', edit_resource_path(resource) %>
  </td>
  <td>
    <%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

site-update_notifier/app/views/resources/_resource_form.html.erb
<%= form_for Resource.new do |f| %>
  <div class="field">
  	<%= f.label :name %>:
    <%= f.text_field :name %>

    <%= f.label :url %>:
    <%= f.text_field :url %>

    <%= f.label :timeout %>:
    <%= f.text_field :timeout %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

site-update_notifier/app/views/resources/_resources_show.html.erb
<div class="user_info_resources">
  <h4>Resources:
    <%= link_to "Add", new_resource_path %>
  </h4>
  
  <% if @user.resources.any? %>
  <table class="table_resource" border="1" bordercolor="#808080" cellspacing="0" cellpadding="10">
  	<tr>
  	  <td><strong>Name of resource</strong></td>
  	  <td><strong>Period </strong></td>
  	  <td><strong>Edit resource</strong></td>
  	  <td><strong>Delete resource</strong></td>
  	</tr>
    <%= render @resources %>
  </table>
  <% end %>
</div>

site-update_notifier/app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', user_path(current_user) %>

site-update_notifier/app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Name</th>
      <th>User</th>
      <th>Timeout</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.url %></td>
        <td><%= resource.name %></td>
        <td><%= resource.user_id %></td>
        <td><%= resource.timeout %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

site-update_notifier/app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(current_user) %>

site-update_notifier/app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @resource.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @resource.user_id %>
</p>

<p>
  <strong>Timeout:</strong>
  <%= @resource.timeout %>
</p>

<p>
  <strong>Change:</strong>
  <%= @resource.change %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', user_path(current_user) %>